import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { PageColorStoreProvider } from '@/providers/page-color.provider'
import { Sidebar } from "@/components/sidebar";
import { Content } from "@/components/content";
import "@/app/globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans"
});

export const metadata: Metadata = {
  title: {
    default: "OT",
    template: "%s | OT"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="dark select-none">
      <body
        className={cn(
          "min-h-screen bg-black font-sans antialiased",
          fontSans.variable,
          "flex"
        )}
      >
        <Sidebar />
        <PageColorStoreProvider>
          <Content>
            {children}
          </Content>
        </PageColorStoreProvider>
      </body>
    </html>
  );
}
